# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `tapioca` gem.
# Please instead update this file by running `bin/tapioca gem tapioca`.


class Tapioca::Error < ::StandardError; end

class Tapioca::Runtime::Trackers::Mixin::Type < ::T::Enum
  enums do
    Extend = new
    Include = new
    Prepend = new
  end
end
