plugins:
  - rubocop-minitest
  - rubocop-rake
  - rubocop-sorbet

inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  Include:
    - "sorbet/rbi/shims/**/*.rbi"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true

Sorbet/EnforceSignatures:
  Style: rbs
  Enabled: true

Sorbet/ForbidTAbsurd:
  Enabled: true

Sorbet/ForbidTBind:
  Enabled: true

Sorbet/ForbidTCast:
  Enabled: true

Sorbet/ForbidTLet:
  Enabled: true

Sorbet/ForbidTMust:
  Enabled: true

Sorbet/ForbidTTypeAlias:
  Enabled: true
